version: "3.8"

services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: ${DOCKER_SERVER_APP_NAME:-spring-backend}
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-8080}/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./demo-app
      dockerfile: Dockerfile
      args:
        - API_URL=http://localhost:${SERVER_PORT:-8080}
    container_name: ${DOCKER_CLIENT_APP_NAME:-spring-frontend}
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge