name: Docker Build Spring Boot (demo)

on:
  push:
    branches: ["main"]
    paths:
      - "demo/**"
      - ".github/workflows/docker-build-demo.yml"
    # Trigger on version tags
    tags:
      - "v*.*.*"
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw clean install --no-transfer-progress
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./demo
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/taskster-backend:latest
            ${{ env.DOCKERHUB_USERNAME }}/taskster-backend:${{ github.sha }}
